In [1]:
import numpy as np

Basics

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
print(a)

[1 2 3]


In [4]:
#list within a list becomes multi dimensional
b= np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b.ndim #get dimension

2

In [6]:
b.shape #get shape

(2, 3)

In [8]:
c= np.array([[1,2,3,2],[1,14,5,6],[12,3,94,2]], dtype='int16')
c

array([[ 1,  2,  3,  2],
       [ 1, 14,  5,  6],
       [12,  3, 94,  2]], dtype=int16)

In [9]:
c.dtype   #get data type

dtype('int16')

In [10]:
b.dtype

dtype('int32')

In [11]:
b.size   #in bytes

6

In [12]:
b.itemsize  #in bytes

4

In [13]:
#total size in bytes
b.size * b.itemsize

24

In [14]:
#total size in bytes
b.nbytes

24

In [16]:
d= np.array([[1.5,2.9],[1.4,14.2]])
d

array([[ 1.5,  2.9],
       [ 1.4, 14.2]])

In [17]:
d.itemsize   #floats take up more than integers

8

Accessing/changing specific elements


https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbDJSQ1BjYzNwazFKUGlSaURXZWlId0U4Wjc4QXxBQ3Jtc0tteWlfS3RlcHlGR0tHaHhKUzc3YzVFcy1kZGV5enRxcDRSSUhJWi1ldTUwU2lCWHp4MlE1Z1BGcVFJYnEtbVNYbUR6ZWU2Wl9Ya1E0S1RBUFo1MmwtcS1BTF8tYW50OTJUeXpPTEZCU2RrMGtuc3daMA&q=https%3A%2F%2Fdocs.scipy.org%2Fdoc%2Fnumpy-1.13.0%2Fuser%2Fbasics.indexing.html

In [18]:
a=np.array([[1,2,3,4,5,6,7],[9,8,7,6,5,4,3]])
a

array([[1, 2, 3, 4, 5, 6, 7],
       [9, 8, 7, 6, 5, 4, 3]])

In [19]:
#get specific element [r,c]
a[1,5]

4

In [20]:
#get specific element [r,c]
# -ve implies from last
a[1,-2]

4

In [21]:
#get whole row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [22]:
#get whole col
a[:,4]

array([5, 5])

In [23]:
# [start:end:step]
a[0,1:4:2]

array([2, 4])

In [24]:
# [start:end:step]
a[0,1:-2:2]

array([2, 4])

In [25]:
a[1,5] =20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 9,  8,  7,  6,  5, 20,  3]])

In [27]:
a[:,3] = 100
a

array([[  1,   2,   3, 100,   5,   6,   7],
       [  9,   8,   7, 100,   5,  20,   3]])

In [28]:
a[:,3] = [400,500]
a

array([[  1,   2,   3, 400,   5,   6,   7],
       [  9,   8,   7, 500,   5,  20,   3]])

In [29]:
#3d array
b=np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
b

array([[[1, 2],
        [3, 4]],

       [[4, 5],
        [6, 7]]])

In [30]:
#get specific element (work from the most outside list)
b[0,1,1]

4

In [31]:
b[0,1,:]

array([3, 4])

In [32]:
b[:,1,:]

array([[3, 4],
       [6, 7]])

In [33]:
b[:,1,1]

array([4, 7])

In [34]:
#change with same dimension
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[4, 5],
        [8, 8]]])

Initializing array


https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbDdoNDViNUFuZkxtOWJJOHM4S253eEIxMGFTQXxBQ3Jtc0trQ2lpMnIwcExQVS1hUlZXdTNVSkpCXzY5dkRnZ2oxeWs4Yl9mekE5OFVJdXByNDNwRUw5OWI3QlVJVzFUVzBEZWhBaU9WUjl3c042cmRuYVd0eERGSjJwd1Q3VVkyMW1wZmg4TXJZd3dYUXlyOHN6Zw&q=https%3A%2F%2Fdocs.scipy.org%2Fdoc%2Fnumpy%2Freference%2Froutines.array-creation.html

In [38]:
#zero matrix
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [40]:
#zero matrix
z = np.zeros((2,3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [41]:
#zero matrix
z = np.zeros((2,3,3))
z

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [42]:
#zero matrix
z = np.zeros((2,3,3,2))
z

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [43]:
#ones matrix
o = np.ones((2,3) , dtype='int32')
o

array([[1, 1, 1],
       [1, 1, 1]])

In [45]:
#any other number
# 2 by 2 of 99
a= np.full((2,2) , 99)
a

array([[99, 99],
       [99, 99]])

In [47]:
np.full(a.shape ,4)

array([[4, 4],
       [4, 4]])

In [48]:
np.full_like(a ,4)

array([[4, 4],
       [4, 4]])

In [50]:
#random decimal nos
np.random.rand(4,3)

array([[0.15632335, 0.16717553, 0.5723685 ],
       [0.23368457, 0.16613605, 0.05202409],
       [0.89235559, 0.5166088 , 0.22904926],
       [0.88916753, 0.13688986, 0.28094279]])

In [51]:
#random decimal nos
np.random.rand(4,3,2)

array([[[0.75981507, 0.94628202],
        [0.76147282, 0.4918481 ],
        [0.45562003, 0.71180693]],

       [[0.29033463, 0.72155033],
        [0.03675079, 0.33692034],
        [0.74188202, 0.28729355]],

       [[0.92815153, 0.2981396 ],
        [0.2217421 , 0.32053665],
        [0.1548545 , 0.65973374]],

       [[0.283105  , 0.23333271],
        [0.96035177, 0.08386305],
        [0.11065162, 0.36694101]]])

In [52]:
#random decimal nos
np.random.random_sample(a.shape)

array([[0.83775825, 0.15890473],
       [0.29670109, 0.57813692]])

In [53]:
#random int nos
np.random.randint(4)  #nos bertween 0 to 3

0

In [54]:
#random int nos
np.random.randint(7, size=(3,3))  # nos between 0 to 6

array([[6, 6, 2],
       [2, 2, 3],
       [4, 3, 2]])

In [55]:
#random int nos
np.random.randint(4,7, size=(3,3))  # nos between 4 to 6

array([[4, 6, 4],
       [4, 4, 6],
       [6, 6, 5]])

In [56]:
#random int nos
np.random.randint(-3,7, size=(3,3))  # nos between -3 to 6

array([[ 0, -2,  6],
       [ 5, -2,  4],
       [ 6,  1,  0]])

In [57]:
#identity 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
#repeat an array
arr =np.array([1,2,3])
r=np.repeat(arr,3)
r

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [59]:
#repeat an array in 2d
arr =np.array([[1,2,3]])
r=np.repeat(arr,3, axis=0)
r

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [60]:
#repeat an array in 2d
arr =np.array([[1,2,3]])
r=np.repeat(arr,3, axis=1)
r

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [63]:
#print specific array

output = np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [64]:
output[1:-1,1:-1]=z

output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

be careful while copying the arrays

In [65]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [66]:
b=a
b

array([1, 2, 3])

In [67]:
b[0]=100
print(b)
print(a)  #a also got changed when we changed b

        # b = a means that b and a are pointing at same location so b changes a changes

[100   2   3]
[100   2   3]


In [69]:
b= a.copy()
b[2]=200
print(b)
print(a)

[100   2 200]
[100   2   3]


Mathematics


https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbXRscWJIRTZoQnRVNms2Nno0M0lpZS03WlFvUXxBQ3Jtc0ttMllYdlpfdFA4T04xLXJvZ1AtS2RrX0hqeXJEam5tQ21aTmVGOTRid3VXQkphZ2xvbjVkNGxnTzkwZ2xkOFZEQ2dYcFo0aVV2YXFMbldkNkZrTmFmR3JsMXVqZDM4UUk1WHU1UmpMNVlvNkJKXzhkNA&q=https%3A%2F%2Fdocs.scipy.org%2Fdoc%2Fnumpy%2Freference%2Froutines.math.html

In [70]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [71]:
a+2

array([3, 4, 5, 6])

In [72]:
a-2

array([-1,  0,  1,  2])

In [73]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [74]:
a*2

array([2, 4, 6, 8])

In [75]:
a+=2
a

array([3, 4, 5, 6])

In [76]:
a**2

array([ 9, 16, 25, 36], dtype=int32)

In [77]:
b=np.array([4,5,6,6])
a+b

array([ 7,  9, 11, 12])

In [78]:
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

In [79]:
np.cos(a)

array([-0.9899925 , -0.65364362,  0.28366219,  0.96017029])

Linear algebra

In [81]:
a = np.ones((2,3))
print(a)


b=np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [82]:
a*b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [83]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [84]:
#determinant
a=np.identity(3)
np.linalg.det(a)

1.0

Statistics

In [85]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
np.min(stats)

1

In [87]:
np.min(stats,axis=1) # min of both rows

array([1, 4])

In [88]:
np.min(stats,axis=0) # min of both cols

array([1, 2, 3])

In [89]:
np.max(stats)

6

In [90]:
np.max(stats,axis=1) # max of both rows

array([3, 6])

In [92]:
np.max(stats,axis=0) # max of both col

array([4, 5, 6])

In [93]:
np.sum(stats)

21

In [94]:
np.sum(stats,axis=1) # sum of both rows

array([ 6, 15])

In [95]:
np.sum(stats,axis=0) # sum of  col

array([5, 7, 9])

Reorganizing array

In [97]:
before = np.array([[1,2,3,4],[3,4,5,6]])
print(before)
print(before.shape)

[[1 2 3 4]
 [3 4 5 6]]
(2, 4)


In [98]:
after = before.reshape(8,1)
after

array([[1],
       [2],
       [3],
       [4],
       [3],
       [4],
       [5],
       [6]])

In [99]:
after = before.reshape(4,2)
after

array([[1, 2],
       [3, 4],
       [3, 4],
       [5, 6]])

In [100]:
after = before.reshape(2,2,2)
after

array([[[1, 2],
        [3, 4]],

       [[3, 4],
        [5, 6]]])

In [102]:
#vertical stack
n1=np.array([1,2,3,4])

n2=np.array([5,6,7,8])

np.vstack((n1,n2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [103]:

np.vstack((n1,n2,n2,n2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [104]:
#horizontal stack


np.hstack((n1,n2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [107]:
#load data from file
data =np.genfromtxt('data.txt',delimiter=',')  #by default float type
data

array([[ 1.,  2.,  3.,  4.,  5.,  6., 67.,  7.],
       [ 1.,  2.,  3.,  4., 45.,  6.,  6.,  7.],
       [ 3.,  3., 44.,  5.,  5.,  5.,  5.,  6.]])

In [108]:
data.astype('int32')

array([[ 1,  2,  3,  4,  5,  6, 67,  7],
       [ 1,  2,  3,  4, 45,  6,  6,  7],
       [ 3,  3, 44,  5,  5,  5,  5,  6]])

boolean masking

In [112]:
data >10

array([[False, False, False, False, False, False,  True, False],
       [False, False, False, False,  True, False, False, False],
       [False, False,  True, False, False, False, False, False]])

In [111]:
data[data>10]

array([67., 45., 44.])

In [114]:
#index using a list
#pass a list

a=np.array([1,2,3,4,5,6,7,8,9])
a[[2,4,6]]

array([3, 5, 7])

In [115]:
np.any(data>10,axis=0)   #tell column wise if any value >10

array([False, False,  True, False,  True, False,  True, False])

In [116]:
np.any(data>10,axis=1)   #tell row wise if any value >10

array([ True,  True,  True])

In [117]:
np.all(data>10,axis=0)   #tell column wise if all value >10

array([False, False, False, False, False, False, False, False])

In [118]:
np.all(data>10,axis=1)   #tell row wise if any value >10

array([False, False, False])

In [119]:
#>10 & <3

((data<3) & (data>10))

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [120]:
# ~>10 & <3
# ~ is not
((data<3) & ~(data>10))

array([[ True,  True, False, False, False, False, False, False],
       [ True,  True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])